acme_api_person:
    pattern:     /upload/person
    defaults: { _controller: AcmeApiBundle:Person:xtractXmlPerson }

acme_api_shiporder:
    pattern:     /upload/shiporder
    defaults: { _controller: AcmeApiBundle:ShipOrder:xtractXmlShipOrder }

acme_api_allperson:
    pattern:     /all/person
    defaults: { _controller: AcmeApiBundle:Person:getAll }


acme_api_allshiporder:
    pattern:     /all/shiporder
    defaults: { _controller: AcmeApiBundle:ShipOrder:getAll }

acme_api_login:
    pattern:     /login
    defaults: { _controller: AcmeApiBundle:Login:login }
# _acme_api:
#      prefix: /upload/shiporder