acme_api_person:
    pattern:     /upload/person
    defaults: { _controller: AcmeApiBundle:Person:xtractXmlPerson }

acme_api_shiporder:
    pattern:     /upload/shiporder
    defaults: { _controller: AcmeApiBundle:ShipOrder:xtractXmlShipOrder }
    

# _acme_api:
#      prefix: /upload/shiporder