acme_api_person:
    path:     /upload/person
    defaults: { _controller: AcmeApiBundle:Person:xtractXmlPerson }

acme_api_shiporder:
    path:     /upload/shiporder
    defaults: { _controller: AcmeApiBundle:ShipOrder:xtractXmlShipOrder }
    

